# Generated by Django 5.0.6 on 2024-05-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="authot",
            new_name="author",
        ),
    ]
